language: ruby
cache:
  bundler: true
  directories:
    - node_modules
sudo: false
script:
  - bundle exec bin/setup
  - bundle exec rake travis:ci
#after_failure:
#  - cat ./log/test.log
env:
  global:
    - CI_NODE_TOTAL=4
  matrix:
    - CI_NODE_INDEX=0
    - CI_NODE_INDEX=1
    - CI_NODE_INDEX=2
    - CI_NODE_INDEX=3
    - JASMINE=true
branches:
  only: # Only build master. Pull requests to master also get built.
    - master
deploy:
  provider: script
  script: bin/ecc-sync
  on:
    branch: master
    repo: nasa/earthdata-search